volumes:
  appCotacaoDb:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: appCotacaoDb

    ports:
      - "5432:5432"

    volumes:
      - appCotacaoDb:/var/lib/postgresql/data